app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import psycopg2
from .config import Config

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config.from_object(Config)


    app.db = connect_db(Config.DB_URI)
    from .routes import main

    app.register_blueprint(main)
    
    return app

def connect_db(db_uri):
    """
    Establish a direct connection to the PostgreSQL database using psycopg2.
    """
    try:
        conn = psycopg2.connect(db_uri)
        return conn
    except Exception as e:
        print(f"Error: Unable to connect to the database. {e}")
        return None

app/routes.py
from flask import Blueprint, json, render_template, request

from app.queries.campaign_insights import get_campaign_insights
from app.queries.campaigns import get_campaings_pagination
from app.queries.dashboard import (
    get_attachment_count,
    get_email_campaigns_count,
    get_email_processed_per_day,
    get_ips_count,
    get_processed_email_count,
    get_receiver_count,
    get_sender_count,
    get_top_campaigns,
    get_top_file_extensions,
    get_top_sender_ips,
    get_top_targeted_domains,
    get_top_url_domains,
)
from app.queries.email_details import (
    get_attachments_for_email,
    get_email_details,
    get_recipients_for_email,
    get_urls_for_email,
)

# Create a Blueprint for the main routes
main = Blueprint("main", __name__)


@main.route("/")
def index():
    all_data = {}
    # Stats
    all_data["sender_count"] = get_sender_count()
    all_data["receiver_count"] = get_receiver_count()
    all_data["processed_email_count"] = get_processed_email_count()
    all_data["email_campaigns_count"] = get_email_campaigns_count()
    all_data["attachment_count"] = get_attachment_count()
    all_data["ips_count"] = get_ips_count()

    # Graphs
    all_data["per_day_email"] = get_email_processed_per_day()
    all_data["top_file_exensions"] = get_top_file_extensions()
    all_data["top_campaigns"] = get_top_campaigns()
    all_data["top_url_domains"] = get_top_url_domains()
    all_data["top_sender_ips"] = get_top_sender_ips()
    all_data["top_targeted_domains"] = get_top_targeted_domains()

    return render_template("index.html", records=all_data)


@main.route("/campaigns")
def campaigns():
    page = request.args.get("page", 1, int)
    size = request.args.get("page", 10, int)
    results, total_records = get_campaings_pagination()
    total_pages = (total_records + size - 1) // size
    return render_template(
        "campaigns.html", records=results, page=page, size=size, total_pages=total_pages
    )


@main.route("/campaigns/<int:id>")
def campaign_insights(id):
    page = request.args.get("page", 1, int)
    size = request.args.get("size", 10, int)
    stats, records, total_records = get_campaign_insights(id, page, size)
    total_pages = (total_records + size - 1) // size

    page_range = list(range(max(1, page - 2), min(total_pages + 1, page + 3)))
    return render_template(
        "campaign_insights.html",
        stats=stats,
        records=records,
        page=page,
        size=size,
        total_pages=total_pages,
        page_range=page_range,
        campaign_id=id,
    )


@main.route("/campaigns/<int:campaign_id>/mails/<int:mail_id>")
def email_details(campaign_id, mail_id):
    record = get_email_details(mail_id)
    if not record:
        pass
    recipients = get_recipients_for_email(mail_id)
    attachments = get_attachments_for_email(mail_id)
    urls = get_urls_for_email(mail_id)
    record["unique_recipients"] = recipients["unique_recipients"] or []

    for _tmp_attachment in attachments:
        for _attachments_details in _tmp_attachment.get("attachments_details") or []:
            if not _attachments_details:
                continue
            if _attachments_details.get("result"):
                _attachments_details["total_av_engines"] = sum(
                    _attachments_details["result"]["analysis_stats"].values()
                )

                _attachments_details["malicious_found"] = (
                    _attachments_details["result"]["analysis_stats"].get("malicious")
                    or 0
                )
    record["attachments_details"] = attachments or []
    record["urls_details"] = urls["urls_details"] or []

    return render_template("email_details.html", record=record)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SHIVA SMTP Honeypot</title>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <!-- Font Awesome Icons -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Chart.js CDN -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <style>
      .card-stat {
        /* border-radius: 12px; */
        background: linear-gradient(45deg, #6a11cb, #2575fc);
        color: #fff;
        /* box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1); */
      }
      .chart-container {
        background-color: #fff;
        border-radius: 12px;
        /* box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5); */
        padding: 20px;
      }
    </style>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">SHIVA SPAMPOT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.endpoint=='main.index' %}active{%endif %}" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.campaigns')}}">Campaigns</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br />
    <!-- MAIN Content -->

    <div class="container-fluid">{% block content %} {% endblock %}</div>

    <!-- Footer -->
    <footer class="mt-auto">
      <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center">
        <p class="h6">© 2025 SHIVA Spampot All right Reserved.</p>
      </div>
      <hr />
    </footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>

  </body>
</html>

app/templates/campaign_insights.html
{% extends 'base.html' %} {% block content%}

<div class="mt-1">
  <div class="row g-2">
    <div class="col-md-3 mb-2 text-center">
      <div class="card card-stat widget-card border-light shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Mails</h5>
          <p class="text-center fw-bold fs-2">{{stats.total_emails}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3 mb-2 text-center">
      <div class="card card-stat widget-card border-light shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Attachments</h5>
          <p class="text-center fw-bold fs-2">{{stats.total_attachments}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3 mb-2 text-center">
      <div class="card card-stat widget-card border-light shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Victims</h5>
          <p class="text-center fw-bold fs-2">{{stats.total_victims}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3 mb-2 text-center">
      <div class="card card-stat widget-card border-light shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Senders</h5>
          <p class="text-center fw-bold fs-2">{{stats.total_attachments}}</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-4">
  <table class="table table-bordered table-hover table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Subject</th>
        <th scope="col">Sender Email</th>
        <th scope="col">Sender IP</th>
        <th scope="col">Total Recipient(s)</th>
        <th scope="col">Total Attachments</th>
        <th scope="col">Send At</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% if records %} {% for record in records %}
      <tr>
        <th scope="row">{{((page -1) * size) + loop.index}}</th>
        <td>{{record.subject}}</td>
        <td>{{record.email}}</td>
        <td>{{record.sender_ip}}</td>
        <td>{{record.recipient_count}}</td>
        <td>{{record.total_attachments}}</td>
        <td>{{record.send_at}}</td>
        <td>
          <a
            href="{{url_for('main.email_details', campaign_id=campaign_id, mail_id=record.id)}}"
            class="btn btn-primary"
            >View More</a
          >
        </td>
      </tr>
      {% endfor %} {% else %}
      <tr class="text-center">
        <td colspan="8">No Records Found</td>
      </tr>
      {% endif %}
    </tbody>
  </table>

  <nav aria-label="Page navigation">
    <ul class="pagination">
      <!-- Previous Page -->
      <li class="page-item {% if page == 1 %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page - 1 }}&size={{ size }}"
          >Previous</a
        >
      </li>
  
      <!-- Page Numbers -->
      {% if page > 3 %}
      <li class="page-item">
        <a class="page-link" href="?page=1&size={{ size }}">1</a>
      </li>
      <li class="page-item disabled">
        <span class="page-link">...</span>
      </li>
      {% endif %} {% for i in page_range %}
      <li class="page-item {% if i == page %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}&size={{ size }}">{{ i }}</a>
      </li>
      {% endfor %} {% if page < total_pages - 2 %}
      <li class="page-item disabled">
        <span class="page-link">...</span>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ total_pages }}&size={{ size }}"
          >{{ total_pages }}</a
        >
      </li>
      {% endif %}
  
      <!-- Next Page -->
      <li class="page-item {% if page == total_pages %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page + 1 }}&size={{ size }}"
          >Next</a
        >
      </li>
    </ul>
  </nav>
  
</div>

{% endblock %}

app/templates/campaigns.html
{% extends 'base.html' %} {% block content%}
<div class="container-fluid mt-4">
  <table class="table table-bordered table-hover table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Subject</th>
        <th scope="col">Total Victims</th>
        <th scope="col">Total Emails</th>
        <th scope="col">Total Attachments</th>
        <th scope="col">Last Mail Sent</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% if records %} {% for record in records %}
      <tr>
        <th scope="row">{{loop.index}}</th>
        <td>{{record.name}}</td>
        <td>{{record.subject}}</td>
        <td>{{record.total_victims}}</td>
        <td>{{record.total_emails}}</td>
        <td>{{record.total_attachments}}</td>
        <td>{{record.timestamp}}</td>
        <td>
          <a
            href="{{url_for('main.campaign_insights', id=record.id)}}"
            class="btn btn-primary"
            >View More</a
          >
        </td>
      </tr>
      {% endfor %} {% else %}
      <tr class="text-center">
        <td colspan="5">No Records Found</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <!-- Previous Page -->
      <li class="page-item {% if page == 1 %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page - 1 }}&size={{ page_size }}"
          >Previous</a
        >
      </li>

      <!-- Page Numbers -->
      {% for i in range(1, total_pages + 1) %}
      <li class="page-item {% if i == page %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}&size={{ page_size }}"
          >{{ i }}</a
        >
      </li>
      {% endfor %}

      <!-- Next Page -->
      <li class="page-item {% if page == total_pages %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page + 1 }}&size={{ page_size }}"
          >Next</a
        >
      </li>
    </ul>
  </nav>
</div>
{% endblock %}

app/templates/email_details.html
{% extends 'base.html' %} {% block content%}
<style>
  .email-details-section {
    background-color: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    margin-bottom: 20px;
  }
  /* .tab-content {
    background-color: #f1f3f5;
    padding: 20px;
    border-radius: 8px;
  } */
  .attachment {
    margin: 10px 0;
  }
  .attachment a {
    color: #007bff;
    text-decoration: none;
  }
  .attachment-meta {
    font-size: 0.9em;
    color: #6c757d;
  }
  .copy-btn {
    cursor: pointer;
    margin-left: 10px;
    color: #007bff;
  }
</style>
<!-- Font Awesome for Icons -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
<div class="container">
  <!-- Email Details Section -->
  <div class="email-details-section">
    <div class="d-flex justify-content-between">
      <h4>Email Details</h4>
      <a href="/path/to/email.eml" download title="Download EML file"><i class="fa-solid fa-download" ></i></a>
    </div>
    <p><strong>From:</strong> <span id="from">{{record.email}}</span></p>
    <p><strong>Sender IP:</strong> <span id="sender_ip">{{record.sender_ip}}</span></p>
    <p><strong>Recipients:</strong> <span id="recipients">{{', '.join(record.unique_recipients)}}</span></p>
    <p><strong>Subject:</strong> <span id="subject">{{record.subject}}</span></p>
    <p><strong>Body:</strong></p>
    <!-- Email Body using <pre> and <code> -->
    <pre><code id="email_body">{{record.email_body}}</code></pre>
  </div>

  <!-- Nav Tabs for IOCs and Attachments -->
   <br>
  <h4 class="mt-4 mb-3">Indicators of Compromise (IOCs)</h4>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link {% if not record.urls_details %}disabled{% else %} active {%endif %}" id="ioc-tab" data-bs-toggle="tab" href="#ioc" role="tab" aria-controls="ioc" aria-selected="true">URL(s)</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link {% if not  record.attachments_details %}disabled {%endif %}" id="attachments-tab" data-bs-toggle="tab" href="#attachments" role="tab" aria-controls="attachments" aria-selected="false">Attachment(s)</a>
    </li>
  </ul>

  <div class="tab-content mt-3" id="myTabContent">
    <!-- IOCs Tab Content -->

    <div class="tab-pane fade show active" id="ioc" role="tabpanel" aria-labelledby="ioc-tab">
      {% if record.urls_details %}
      <ul class="list-group">
      {% for urls_detail in record.urls_details %}
          <li class="list-group-item">
          <div >
            <strong>URL: </strong> <a href="{{urls_detail.url}}" id="ioc_url">{{urls_detail.url}}</a> <i class="fa fa-copy copy-btn" onclick="copyText('#ioc_url')"></i> 
            <br><strong>Domain: </strong>{{urls_detail.domain}} 
            <br><strong>SHA256: </strong> <code id="url1_sha256">{{urls_detail.url_sha256}}</code> <i class="fa fa-copy copy-btn" onclick="copyText('#url1_sha256')"></i>
          </div>
        </li>
      </ul>
      {% endfor %}
      {% endif %}
    </div>

    <!-- Attachments Tab Content -->
    <div class="tab-pane fade" id="attachments" role="tabpanel" aria-labelledby="attachments-tab">
      {% if record.attachments_details %}
      <ul class="list-group">
      {% for attachments_details in record.attachments_details %}
          <li class="list-group-item">
          <div>
            <strong>Name: </strong>{{attachments_details.file_name}} <a href="{{attachments_details.attachment_file_url}}" download><i class="fa-solid fa-download"></i></a>
            <br><strong>SHA256: </strong> <code id="attachment1_sha256">{{attachments_details.file_sha256}}</code> <i class="fa fa-copy copy-btn" onclick="copyText('#attachment1_sha256')"></i>
            <br><strong>Type: </strong>{{attachments_details.file_extension}} 

            {% if attachments_details.file_size < 1024 %}
                {% set file_size = attachments_details.file_size %}
                {% set unit = 'Bytes' %}
            {% elif attachments_details.file_size < 1024 * 1024 %}
                {% set file_size = attachments_details.file_size / 1024 %}
                {% set unit = 'KB' %}
            {% elif attachments_details.file_size < 1024 * 1024 * 1024 %}
                {% set file_size = attachments_details.file_size / (1024 * 1024) %}
                {% set unit = 'MB' %}
            {% else %}
                {% set file_size = attachments_details.file_size / (1024 * 1024 * 1024) %}
                {% set unit = 'GB' %}
            {% endif %}

            <br><strong>Size: </strong>{{ file_size | round(2) }} {{ unit }} 
            {% if attachments_details.attachments_details %}
            {% set att_analysis = attachments_details.attachments_details[0] %}
            {% if att_analysis %}
            <p><strong>Analysis Results:</strong></p>
            <ul class="list-group">
              <li class="list-group-item">
                <strong>VirusTotal:</strong>
                <p>Is Malicious: {% if att_analysis.is_malicious %}
                  <span class="text-danger">Yes</span>
                  {% else %}
                  No
                  {% endif %}
                </p>
                <p>{{att_analysis.malicious_found}} out of {{att_analysis.total_av_engines}} Security Vendors detected the file as malicious.</p>
              </li>
            </ul>
            {% endif %}
            {% endif %}
          </div>
        </li>
      </ul>

      {% endfor %}

      {% endif %}
      
    </div>
  </div>
</div>


<script>
  function copyText(elementId) {
    const text = document.querySelector(elementId).textContent || document.querySelector(elementId).innerText;
    navigator.clipboard.writeText(text).then(() => {
      alert('Copied to clipboard!');
    }).catch(err => {
      alert('Failed to copy: ' + err);
    });
  }

</script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block content%}
<div class="mt-1">
  <div class="row g-2">
    <div class="col-md-2 text-center">
      <div class="card card-stat widget-card border-light">
        <div class="card-body">
          <h5 class="card-title">Unique IPs</h5>
          <p class="text-center fw-bold fs-2">{{records.ips_count}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-2 text-center">
      <div class="card card-stat widget-card border-light">
        <div class="card-body">
          <h5 class="card-title">Unique Senders</h5>
          <p class="text-center fw-bold fs-2">{{records.sender_count}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-2 text-center">
      <div class="card card-stat widget-card border-light">
        <div class="card-body">
          <h5 class="card-title">Unique Recipient</h5>
          <p class="text-center fw-bold fs-2">{{records.receiver_count}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-2 text-center">
      <div class="card card-stat widget-card border-light">
        <div class="card-body">
          <h5 class="card-title">Emails Processed</h5>
          <p class="text-center fw-bold fs-2">
            {{records.processed_email_count}}
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-2 text-center">
      <div class="card card-stat widget-card border-light">
        <div class="card-body">
          <h5 class="card-title">Campaigns Detected</h5>
          <p class="text-center fw-bold fs-2">
            {{records.email_campaigns_count}}
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-2 text-center">
      <div class="card card-stat widget-card border-light">
        <div class="card-body">
          <h5 class="card-title">Attachments</h5>
          <p class="text-center fw-bold fs-2">{{records.attachment_count}}</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <!-- Charts Section -->
    <div class="col-md-4">
      <div class="card">
      <div class="card-body">
        <div id="email_processed_chart"></div>
      </div>
      </div>
    </div>

    <div class="col-md-4 ps-0 pe-0">
      <div class="card">
      <div class="card-body">
        <div id="campaign_heatmap"></div>
      </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
      <div class="card-body">
        <div id="file_extension_chart"></div>
      </div>
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md-3 pe-0">
      <div class="card">
      <div class="card-body">
        <div id="top_target_domains"></div>
      </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
      <div class="card-body">
        <div id="top_source_ip_chart"></div>
      </div>
      </div>
    </div>

    <div class="col-md-3 ps-0">
      <div class="card">
      <div class="card-body">
        <div id="top_url_domain_chart" class="h-100"></div>
      </div>
      </div>
    </div>
  </div>
</div>

<script>
  // EMAIL PROCESSED START
  var email_processed_chart_options = {
    series: [
      {
        name: "Mail Recieved",
        data: {{ records.per_day_email.data | tojson }},
      },
    ],
    chart: {
      height: 350,
      type: "line",
      zoom: {
        enabled: false,
      },
      toolbar: { show: false },
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      curve: "smooth",
    },
    title: {
      text: "Mails Processed per Day",
      align: "center",
    },
    xaxis: {
      categories: {{ records.per_day_email.labels | tojson }},
    },
  };

  var chart = new ApexCharts(
    document.getElementById("email_processed_chart"),
    email_processed_chart_options
  );
  chart.render();
  // EMAIL PROCESSED END

  // campaign_heatmap START
  var campaign_heatmap_options = {
    series: [
      {
        data: {{records.top_campaigns | tojson}}
      },
    ],
    legend: {
      show: false,
    },
    chart: {
      height: 350,
      type: "treemap",
      toolbar: { show: false },
    },
    title: {
      text: "Campaigns Overview",
      align:'center'
    },
  };
  var chart = new ApexCharts(
    document.getElementById("campaign_heatmap"),
    campaign_heatmap_options
  );
  chart.render();
  // campaign_heatmap END

  // file_extension_chart START
  var file_extension_chart_options = {
    series: [
      {
        name: "Extension",
        data: {{ records.top_file_exensions.data | tojson }},
      },
    ],
    chart: {
      height: 350,
      type: "bar",
      toolbar: {
        show: false,
      },
    },
    plotOptions: {
      bar: {
        borderRadius: 1,
        columnWidth: "50%",
      },
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      width: 0,
    },
    title: {
      text: "Top 10 File Extensions",
      align: "center",
    },
    xaxis: {
      labels: {
        rotate: -45,
      },
      categories: {{ records.top_file_exensions.labels | tojson }},
      tickPlacement: "on",
    },
    fill: {
      type: "gradient",
      gradient: {
        shade: "light",
        type: "horizontal",
      },
    },
  };

  var chart = new ApexCharts(
    document.getElementById("file_extension_chart"),
    file_extension_chart_options
  );
  chart.render();
  // file_extension_chart END

  // top_target_domains START
  var top_target_domains_options = {
    series: {{ records.top_targeted_domains.data | tojson }},
    chart: {
      type: "donut",
    },
    labels: {{ records.top_targeted_domains.labels | tojson }},
    dataLabels: {
      enabled: false,
    },
    responsive: [
      {
        breakpoint: 480,
        options: {
          chart: {
            width: 200,
          },
          legend: {
            position: "bottom",
          },
        },
      },
    ],
    title: {
      text: "Target Domains",
      align: "center",
    },
  };

  var chart = new ApexCharts(
    document.getElementById("top_target_domains"),
    top_target_domains_options
  );
  chart.render();
  // top_target_domains END

  // Top Sender IPs START
  var top_source_ip_chart_options = {
    series: [
      {
        name: "IP",
        data: {{ records.top_sender_ips.data | tojson }},
      },
    ],
    chart: {
      height: 215,
      type: "bar",
      toolbar: {
        show: false,
      },
    },
    plotOptions: {
      bar: {
        borderRadius: 1,
        columnWidth: "50%",
      },
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      width: 0,
    },
    title: {
      text: "Top 10 Sender IPs",
      align: "center",
    },
    xaxis: {
      categories: {{ records.top_sender_ips.labels | tojson }},
      tickPlacement: "on",
    },
    fill: {
      type: "gradient",
      gradient: {
        shade: "light",
        type: "horizontal",
      },
    },
  };

  var chart = new ApexCharts(
    document.getElementById("top_source_ip_chart"),
    top_source_ip_chart_options
  );
  chart.render();

  // Top Sender IPs END


  // Top Url's Domain START
  var top_url_domain_chart_options = {
    series: {{ records.top_url_domains.data | tojson }},
    chart: {
      type: "pie",
    },
    labels: {{ records.top_url_domains.labels | tojson }},
    dataLabels: {
      enabled: false,
    },
    responsive: [
      {
        breakpoint: 480,
        options: {
          chart: {
            width: 200,
          },
          legend: {
            position: "bottom",
          },
        },
      },
    ],
    title: {
      text: "Top URL's Domain",
      align: "center",
    },
  };

  var chart = new ApexCharts(
    document.getElementById("top_url_domain_chart"),
    top_url_domain_chart_options
  );
  chart.render();
  // Top Url's Domain END
</script>

{% endblock %}